name: Merge Release to Main

on:
  push:
    branches:
      - "release/*"
jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge release branch into main
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff ${GITHUB_REF_NAME} -m "Merging release branch ${GITHUB_REF_NAME} into main"
          git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
