name: Linting SpringBoot API Codebase

on:
  push:
    branches:
      - "dev/**"
      - "staged/**"
    paths:
      - "spring-boot-api/src/**"
      - "spring-boot-api/pom.xml"
      - ".github/workflows/**"
  pull_request:
    branches:
      - "dev/**"
      - "staged/**"
    paths:
      - "spring-boot-api/src/**"
      - "spring-boot-api/pom.xml"
      - ".github/workflows/**"
jobs:
  linting-api-codebase:
    name: Linting SpringBootAPI Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "21"
          
      - name: Set up toolchains.xml
        run: |
          mkdir -p ~/.m2
          cp .m2/toolchains.xml ~/.m2/toolchains.xml

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: Build project (skip testing)
        run: "cd ./spring-boot-api && mvn clean install -DskipTests"
        
      - name: Run Linter
        run: "cd ./spring-boot-api && mvn validate"
